# Generated by Django 5.0.7 on 2024-07-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProductos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
    ]
